### ISSUE TITLE
Dependency to unit-threaded causes issue

### ISSUE THREAD

**Issue by andre2007** [linkrope/dunit#12]
d-unit has a dependency to unit-threaded this causes issues. I created a XMake build infrastructure. There is a golden rule, that during the build, the internet must not be accessed. Therefore I fetched d-unit upfront and placed it within my dub package folder. Within dub.json I specified the dependency to d-unit via the "path" attribute.

While executing dub build, there is now an error thrown
> Could not find a valid dependency tree configuration: Package d-unit contains invalid dependency
> unit-threaded (no version candidates)

Although I do not use this configuration, dub will check the dependency and will fail the build.
Could you check whether you can enabled fluent assertions without having a dependency to unit-threaded?
d-unit is such an important library, it would be nice if it is completely independent.

**Comment by andre2007** [comment]
A solution could be to set the dependency to unit-threaded as optional like described here
https://code.dlang.org/package-format?lang=json

**Comment by linkrope** [comment]
Does the latest simplified `dub.json` work for you?

**Comment by andre2007** [comment]
yes, thanks a lot:)
