### ISSUE TITLE
Create folder(s) for report argument

### ISSUE THREAD

**Issue by andre2007** [linkrope/dunit#15]
While passing a file path via console argument "report" there is an exception thrown if the folder does not exist.

```
dub test -- --report results/junit.xml
```
Could you create the folder(s) instead of throwing an exception?

**Comment by linkrope** [comment]
This behavior is based on the UNIX style:

    $ mv foo bar/foo
    mv: cannot move 'foo' to 'bar/foo': No such file or directory

The dmd itself supports both approaches:
- with option `-of=<filename>` missing directories are created
- with option `-deps=<filename>` you get _Error writing file 'bar/foo'_

In our build file, it was easy enough to add a dependency on the directory.
So, the build tool creates the directory for the test report (as well as for the object files and the dependencies).

On the other hand, the standard library already provides `std.file.mkdirRecurse`.
If you create pull request, I will accept it.

**Comment by andre2007** [comment]
I created pull request #16. Could you also check whether you can provide a new release?
Thanks a lot.
