### ISSUE TITLE
Having trouble running any tests

### ISSUE THREAD

**Issue by vsajip** [linkrope/dunit#22]
It's probably something dumb I'm doing, so I'd appreciate any pointers - I'm fairly new to D and `dub`. Here's my `dub.json`:
```
{
  "name": "dconfig",
  "authors": [
    "Vinay Sajip"
  ],
  "description": "A test.",
  "dependencies": {
    "d-unit": "~>0.9.0"
  }
}
```
and here's my test code:
```
module tests;

import dunit;

class MyFirstTest {

    mixin UnitTest;

    @Test
    public void shouldFail()
    {
        string expected = "bar";
        string actual = "baz";

        assertEquals(expected, actual);
    }
}
```
When I run `dub test`, I get:
```
Generating test runner configuration 'dconfig-test-library' for 'library' (library).
Performing "unittest" build using /usr/bin/dmd for x86_64.
d-unit 0.9.0: target for configuration "library" is up to date.
dconfig ~master: building configuration "dconfig-test-library"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./dconfig-test-library 
All unit tests have been run successfully.
```
But nothing seems to run, since no failure is printed. The `dconfig-test-library` certainly seems to contain the symbols for `MyFirstTest` and `shouldFail`, so why would the test not be run?

The D version is `DMD64 D Compiler v2.082.0`, running on Ubuntu 16.04.

By the way, your `example.d` shows a `mixin Main;`, but I've omitted that since it doesn't seem to be needed to bring a `main` in. In fact, adding it causes a build failure due to `Error: only one main allowed.`

**Comment by linkrope** [comment]
You have to run `unit_main` from `dunit.framework`. There are, however, several ways to do this:
- put the call `unit_main(args);` in your `main` function
- use `version (unittest) ... else ...` to select either `mixin Main;` or your own `main` function
- use different `dub` "configurations" for your executable and for the test runner
  (move the test-runner `main` for example from `source` to `unittest/main.d` and specify it explicitly as "mainSourceFile")

**Comment by vsajip** [comment]
Thanks. I figured it out and used the first option.
