### ISSUE TITLE
Program exited with code -11: @BeforeAll

### ISSUE THREAD

**Issue by andre2007** [linkrope/dunit#27]
By adding a `@BeforeAll` method to my class (independent whether beforeAll method is marked as static or not) the application crashes with `Program exited with code -11` on ubuntu 18.

```d
import dunit;

class OperatorTests
{
    mixin UnitTest;

    @BeforeAll void beforeAll(){}
    @Test void test1(){}
}
```

**Comment by linkrope** [comment]
There is a `@BeforeAll` in the example:
https://github.com/linkrope/dunit/blob/master/example.d#L80-L84

Does this also crash on your machine?

    $ ./example.d
    ...
    Tests run: 14, Failures: 4, Errors: 1, Skips: 1
    NOT OK
    Program exited with code 1

**Comment by andre2007** [comment]
I just found out, it is related to the function name. `beforeAll` causes a crash, while `beforeAll1` and anything else is working fine. Therefore the sample is workink, due to the name `setUpAll`.
