### ISSUE TITLE
Location is not clickable in Visual Studio Code terminal

### ISSUE THREAD

**Issue by andre2007** [linkrope/dunit#28]
I execute `dub test` and get following output in the terminal of Visual Studio Code

```
There was 1 failure:
1) client.tests.tasks.login.LoginV3Test.askForApiEndpoint
dunit.assertion.AssertException@source/client/tests/tasks/login.d(54): expected: <<https://myapi/v3>> but was: <<>>
```

Visual Studio Code automatically enables forward navigation to line 54 of source code file  `source/client/tests/tasks/login.d` if the output e.g. looks like this:
```
There was 1 failure:
1) client.tests.tasks.login.LoginV3Test.askForApiEndpoint
source/client/tests/tasks/login.d(54): expected: 
<<https://myapi/v3>> but was: <<>>
```

The `@` character before the source file location is an issue.
Do you see any chance to change the output to a VSC friendly format?

**Comment by linkrope** [comment]
By the way: `@` is used in `Throwable.toString` in `object.d`.
Also, I had to replace `example.d:42` by `./example.d:42`, but trace info still shows `example.d:42` (not clickable).

**Comment by andre2007** [comment]
Thanks a lot.
